[scheduler]
    thread_num = 20
    process_num = 5
    coalesce = false
    max_instances = 5

[log]
    prefix = "scheduler"
    level = 4
    path = "./log"

[manager]
interface = "eth0"
port = 7070

[[manager.queue]]
id = "test_thread"
size = 1024
func = "get_test_task_queue"


[[manager.queue]]
id = "test_thread"
size = 1024
func = "get_test_result_queue"

[[manager.worker]]
id = "test_thread"
number = 3
func = "src.test"

[[jobs]]
    trigger = "interval"
    id = "test_thread"
    func = "src.test:test_thread"
    seconds = 2

[[jobs]]
    trigger = "interval"
    id = "test_process"
    func = "src.test:test_process"
    seconds = 3
    executor = "processpool"

[global]
[[global.region]]
    key = "ap-guangzhou"
    name = "广州"
    short_name = "gz"
    id = 1
    file = "region/ap-guangzhou.toml"


